import { OUTSIDE_PURCHASE_STAFF_NOTE_PREFIX } from "@/lib/outside-purchase-staff-note";
import { OUTSIDE_PURCHASE_RETURN_ESTIMATE_DEFAULT_STAFF_NOTE } from "@/lib/outside-purchase-return-preview-copy";

export const RETURN_SERVICE_HANDLING_NOTE_PREFIX = "Return service & handling:";

const STRUCTURED_FIELD_PREFIXES: { prefix: string; label: string }[] = [
  { prefix: "Receipt note:", label: "Receipt note" },
  { prefix: "Received condition:", label: "Received condition" },
  { prefix: "Shelf / bin:", label: "Shelf / bin" },
  {
    prefix: "Outside purchase service & handling:",
    label: "Service & handling",
  },
  { prefix: RETURN_SERVICE_HANDLING_NOTE_PREFIX, label: "Return service & handling" },
  { prefix: "Listed unit price for tier:", label: "Listed unit price (tier)" },
];

export type OutsidePurchaseStaffNoteField = {
  label: string;
  value: string;
};

/** Auto-generated return estimate fee line appended when staff publish a return quote. */
export function isReturnServiceHandlingFeeLine(line: string): boolean {
  return line.trim().startsWith(RETURN_SERVICE_HANDLING_NOTE_PREFIX);
}

/** Default/custom staff copy shown above the return fee breakdown. */
export function isReturnEstimatePolicyParagraph(text: string): boolean {
  const normalized = text.trim().toLowerCase();
  if (!normalized) return false;
  return (
    normalized ===
      OUTSIDE_PURCHASE_RETURN_ESTIMATE_DEFAULT_STAFF_NOTE.trim().toLowerCase() ||
    normalized.startsWith(
      "returned fee must be paid before items can be drop off",
    )
  );
}

function splitStaffNoteParagraphs(note: string): string[] {
  return note
    .split(/\n\n+/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean);
}

/** Removes every prior return estimate policy/fee block from a saved staff note. */
export function stripSupersededReturnEstimateNoteContent(note: string): string {
  const kept: string[] = [];

  for (const paragraph of splitStaffNoteParagraphs(note)) {
    const lines = paragraph
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);
    const filteredLines = lines.filter(
      (line) =>
        !isReturnServiceHandlingFeeLine(line) &&
        !isReturnEstimatePolicyParagraph(line),
    );

    if (filteredLines.length === 0) continue;
    if (filteredLines.length === lines.length) {
      kept.push(paragraph);
    } else {
      kept.push(filteredLines.join("\n"));
    }
  }

  return kept.join("\n\n");
}

/** Keeps only the latest return estimate policy + fee breakdown for display/saves. */
export function noteWithLatestReturnEstimateOnly(note: string): string {
  const trimmed = note.trim();
  if (!trimmed) return trimmed;

  let latestPolicy: string | null = null;
  let latestFeeLine: string | null = null;

  for (const paragraph of splitStaffNoteParagraphs(trimmed)) {
    if (isReturnServiceHandlingFeeLine(paragraph)) {
      latestFeeLine = paragraph.trim();
      continue;
    }
    if (isReturnEstimatePolicyParagraph(paragraph)) {
      latestPolicy = paragraph.trim();
      continue;
    }

    for (const line of paragraph.split("\n").map((entry) => entry.trim()).filter(Boolean)) {
      if (isReturnServiceHandlingFeeLine(line)) {
        latestFeeLine = line;
      } else if (isReturnEstimatePolicyParagraph(line)) {
        latestPolicy = line;
      }
    }
  }

  const withoutReturn = stripSupersededReturnEstimateNoteContent(trimmed);
  if (!latestFeeLine) return withoutReturn;

  const latestBlock = [latestPolicy, latestFeeLine].filter(Boolean).join("\n\n");
  return withoutReturn.trim() ?
      `${withoutReturn.trim()}\n\n${latestBlock}`
    : latestBlock;
}

/** True when a single line is policy copy or auto-generated intake/pricing metadata. */
export function isOutsidePurchaseAutoGeneratedLine(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed) return true;
  if (trimmed.startsWith(OUTSIDE_PURCHASE_STAFF_NOTE_PREFIX)) return true;
  if (isReturnServiceHandlingFeeLine(trimmed)) return true;
  if (isReturnEstimatePolicyParagraph(trimmed)) return true;
  if (trimmed === "(customer pays)." || trimmed === "(customer pays)") return true;
  return STRUCTURED_FIELD_PREFIXES.some(({ prefix }) => trimmed.startsWith(prefix));
}

/** True when a paragraph is policy copy or auto-generated intake/pricing lines. */
export function isOutsidePurchaseAutoGeneratedParagraph(
  paragraph: string,
): boolean {
  const trimmed = paragraph.trim();
  if (!trimmed) return true;
  if (trimmed.startsWith(OUTSIDE_PURCHASE_STAFF_NOTE_PREFIX)) return true;

  const lines = trimmed
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) return true;

  return lines.every((line) => isOutsidePurchaseAutoGeneratedLine(line));
}

/** Customer-facing freeform staff messages (excludes intake/pricing metadata). */
export function outsidePurchaseCustomStaffMessages(
  note: string | null | undefined,
): string[] {
  if (!note?.trim()) return [];

  const parsed = parseOutsidePurchaseStaffNoteDisplay(note);
  const messages: string[] = [];

  for (const paragraph of parsed.freeformParagraphs) {
    const customLines = paragraph
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line && !isOutsidePurchaseAutoGeneratedLine(line));
    if (customLines.length > 0) {
      messages.push(customLines.join("\n"));
    }
  }

  const seen = new Set<string>();
  return messages.filter((message) => {
    const key = message.trim().toLowerCase();
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function tryParseStructuredFieldLine(
  line: string,
): OutsidePurchaseStaffNoteField | null {
  const trimmed = line.trim();
  if (!trimmed) return null;
  for (const { prefix, label } of STRUCTURED_FIELD_PREFIXES) {
    if (trimmed.startsWith(prefix)) {
      return {
        label,
        value: stripTrailingPeriod(trimmed.slice(prefix.length)),
      };
    }
  }
  return null;
}

function appendStructuredFieldLine(
  fields: OutsidePurchaseStaffNoteField[],
  line: string,
): boolean {
  const parsed = tryParseStructuredFieldLine(line);
  if (!parsed) return false;
  fields.push(parsed);
  return true;
}

/** Split mixed policy tail / paragraph text into structured fields vs custom copy. */
function ingestMultilineStaffNoteText(
  text: string,
  fields: OutsidePurchaseStaffNoteField[],
  freeformParagraphs: string[],
): void {
  const customLines: string[] = [];
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || isOutsidePurchaseAutoGeneratedLine(trimmed)) {
      if (trimmed && appendStructuredFieldLine(fields, trimmed)) continue;
      continue;
    }
    if (!appendStructuredFieldLine(fields, trimmed)) {
      customLines.push(trimmed);
    }
  }
  if (customLines.length > 0) {
    freeformParagraphs.push(customLines.join("\n"));
  }
}

function stripTrailingPeriod(value: string): string {
  return value.replace(/\.\s*$/, "").trim();
}

function isPackMetaParagraph(paragraph: string): boolean {
  return /^\[op-pack\]\s*unitsPerPack=\d+$/i.test(paragraph.trim());
}

/** Split outside-purchase staff notes into policy copy, labeled fields, and freeform text. */
export function parseOutsidePurchaseStaffNoteDisplay(note: string): {
  policyNotice: string | null;
  fields: OutsidePurchaseStaffNoteField[];
  freeformParagraphs: string[];
} {
  const trimmed = noteWithLatestReturnEstimateOnly(note.trim());
  if (!trimmed) {
    return { policyNotice: null, fields: [], freeformParagraphs: [] };
  }

  const paragraphs = trimmed
    .split(/\n\n+/)
    .map((paragraph) => paragraph.trim())
    .filter(Boolean)
    .filter((paragraph) => !isPackMetaParagraph(paragraph));

  let policyNotice: string | null = null;
  const fields: OutsidePurchaseStaffNoteField[] = [];
  const freeformParagraphs: string[] = [];

  for (const paragraph of paragraphs) {
    if (
      !policyNotice &&
      paragraph.startsWith(OUTSIDE_PURCHASE_STAFF_NOTE_PREFIX)
    ) {
      policyNotice = OUTSIDE_PURCHASE_STAFF_NOTE_PREFIX;
      const remainder = paragraph
        .slice(OUTSIDE_PURCHASE_STAFF_NOTE_PREFIX.length)
        .trim();
      if (remainder) {
        ingestMultilineStaffNoteText(remainder, fields, freeformParagraphs);
      }
      continue;
    }

    let matchedField = false;
    for (const { prefix, label } of STRUCTURED_FIELD_PREFIXES) {
      if (paragraph.startsWith(prefix)) {
        fields.push({
          label,
          value: stripTrailingPeriod(paragraph.slice(prefix.length)),
        });
        matchedField = true;
        break;
      }
    }
    if (!matchedField) {
      if (paragraph.includes("\n")) {
        ingestMultilineStaffNoteText(paragraph, fields, freeformParagraphs);
      } else {
        freeformParagraphs.push(paragraph);
      }
    }
  }

  return {
    policyNotice,
    fields: dedupeStaffNoteFieldsByLabel(fields),
    freeformParagraphs: dedupeReturnEstimateFreeformParagraphs(
      dedupeFreeformParagraphs(freeformParagraphs),
      fields.some((field) => field.label === "Return service & handling"),
    ),
  };
}

function dedupeReturnEstimateFreeformParagraphs(
  paragraphs: string[],
  hasReturnFeeField: boolean,
): string[] {
  if (!hasReturnFeeField) {
    return paragraphs.filter((paragraph) => !isReturnEstimatePolicyParagraph(paragraph));
  }

  let policyShown = false;
  return paragraphs.filter((paragraph) => {
    const trimmed = paragraph.trim();
    if (isReturnServiceHandlingFeeLine(trimmed)) return false;
    if (!isReturnEstimatePolicyParagraph(trimmed)) return true;
    if (policyShown) return false;
    policyShown = true;
    return true;
  });
}

function dedupeFreeformParagraphs(paragraphs: string[]): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const paragraph of paragraphs) {
    const key = paragraph.trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    result.push(paragraph);
  }
  return result;
}

function preferOutsidePurchaseStaffNoteField(
  next: OutsidePurchaseStaffNoteField,
  prev: OutsidePurchaseStaffNoteField,
): boolean {
  if (
    next.label === "Return service & handling" ||
    next.label === "Service & handling" ||
    next.label === "Listed unit price (tier)"
  ) {
    if (next.label === "Return service & handling") {
      return true;
    }
    const nextZero = /\$0\.00/.test(next.value);
    const prevZero = /\$0\.00/.test(prev.value);
    if (nextZero !== prevZero) return !nextZero;
  }
  return true;
}

function dedupeStaffNoteFieldsByLabel(
  fields: OutsidePurchaseStaffNoteField[],
): OutsidePurchaseStaffNoteField[] {
  const byLabel = new Map<string, OutsidePurchaseStaffNoteField>();
  for (const field of fields) {
    const prev = byLabel.get(field.label);
    if (!prev || preferOutsidePurchaseStaffNoteField(field, prev)) {
      byLabel.set(field.label, field);
    }
  }
  const emitted = new Set<string>();
  const result: OutsidePurchaseStaffNoteField[] = [];
  for (const field of fields) {
    if (emitted.has(field.label)) continue;
    emitted.add(field.label);
    result.push(byLabel.get(field.label)!);
  }
  return result;
}

export function hasStructuredOutsidePurchaseStaffNote(note: string): boolean {
  const parsed = parseOutsidePurchaseStaffNoteDisplay(note);
  return (
    parsed.policyNotice != null ||
    parsed.fields.length > 0 ||
    parsed.freeformParagraphs.some((paragraph) => paragraph.trim().length > 0)
  );
}
